### ISSUE TITLE
EPUB Downloading issue

### ISSUE THREAD

**Issue by hvmzx** [Banh-Canh/docker-FMD2#12]
Hi,

When downloading files in .cbz it works very well but in .epub it generates a very tiny file that seems broken and unopenable. I tried that with multiple chapters and I get the same result.

Also would love to see .epub downloading with correct metadata from fields like Chapters, author ...

**Comment by Banh-Canh** [comment]
I can't support this, you should try using FMD2 directly and ask in the main repository project if the problem persists .
