### ISSUE TITLE
Wrong Volume Sync ?

### ISSUE THREAD

**Issue by ElryWeeb** [Banh-Canh/docker-FMD2#16]
The Files / Folders in the Container are out of Sync to the mapped output folder.

Here the Comparison:
![image](https://github.com/Banh-Canh/docker-FMD2/assets/144011449/ea2292bd-9ff1-4f18-9792-a5b009660d7a)

You can see how in the Output i have images and 2 chapters are missing, while inside the container everything looks normal ?

**Comment by ElryWeeb** [comment]
Ok this seems to be related to https://github.com/Banh-Canh/docker-FMD2/issues/9
Im using kasm-v3 and the default is still downloads/ and not Z:/downloads, after changing it to that its fixed.

**Comment by CuteNikki** [comment]
Its actually https://github.com/Banh-Canh/docker-FMD2/issues/13
BTW your script to move the files does not work on a single branch, i tried latest, kasm-3, kasm-2 & kasm-exp......

**Comment by Banh-Canh** [comment]
you have to set fmd2 to save to "downloads\" nothing more nothing less using kasmv3.
then you bind mount to "/downloads".

i can't support the old ways since wine6++ changed how it used to work

**Comment by ElryWeeb** [comment]
yeah that would be cool and working, if your script would move all the files and not stop halfway trough.
I decided to use tranga instead now.

**Comment by Banh-Canh** [comment]
have fun then.

**Comment by Banh-Canh** [comment]
It does not, also you can use the following relative to fmd2 path which is the default in newer version: `downloads\` which will effectively downloads to `Z:\app\FMD2\downloads\`.
if you take a look at the PR's code you would see that it does not change any of this but do improve in some other ways.
This project is still a workaround for lack of linux support from the upstream app FMD2.
Now, you can move wherever you want. I don't owe you anything, have fun wherever you go. 

All the bests

**Comment by ElryWeeb** [comment]
I dont mean you harm if it sounded like that, i wouldnt want to move back to your repo if that would be the case ^^
Just that downloads thing does not work for me, it stops halway trough moving the files, and also moves the images etc.
While the PR fixes all problems i had with it.
