### ISSUE TITLE
Script not moving files

### ISSUE THREAD

**Issue by ElryWeeb** [Banh-Canh/docker-FMD2#19]
i used the repo from @Jerrk without problems, but your updated kasm-v3 docker still has the same problem of it not moving files.

**Comment by ElryWeeb** [comment]
Even when cloning the kasm-v3 repo, it seems to not work properly.

**Comment by hotsno** [comment]
Having the same issue, however latest commit of @Jerrk's repo doesn't work for me either.

https://github.com/Banh-Canh/docker-FMD2/pull/17#issuecomment-1955675325

**Comment by hotsno** [comment]
Update: https://github.com/Banh-Canh/docker-FMD2/pull/17#issuecomment-1958025423

**Comment by ElryWeeb** [comment]
Yeah that fixed it
