### ISSUE TITLE
[REFACTOR] Use Linux native version of FMD2

### ISSUE THREAD

**Issue by Banh-Canh** [Banh-Canh/docker-FMD2#2]
I'm going to need to compile it inside the container since there is no linux release

**Comment by hazre** [comment]
have you had any luck compiling it for linux yet?

**Comment by Banh-Canh** [comment]
Hello, I haven't been bothered to look into this just yet. tbh I'm not sure it is possible, I didn't see many feedbacks about that on the fmd2 project so idk. But if it is, I could try

**Comment by hazre** [comment]
Yeah I couldn't find anything on it either, so im assuming no one has tried it yet. But it seems possible, only issue is I have no clue how lazarus works, so idk how to complie it..

**Comment by SituesmonpainJetejetterai** [comment]
Hi, is there any progress on this front? Wine is fine and all but part of me really wants a linux-native build; if you could compile it, you might even be able to open a new repository for the linux build of FMD2!

**Comment by HamzaM** [comment]
> 

This would really be good because this wine part is quite bothersome.

**Comment by Banh-Canh** [comment]
Gave it a try, too much code to change. The main project use some windows specific library, i don't know Pascal enough. I tried hard to write in some hack here and there but I didn't achieve any good result. I was able to compile it, so maybe if someone know Pascal can help we can figure something out. Closing
