### ISSUE TITLE
Change width/height of the vnc window?

### ISSUE THREAD

**Issue by Jerrk** [Banh-Canh/docker-FMD2#6]
i use a portrait monitor for all my webuis and i haven't ran into this problem yet.

the default window size seem to be some flavour of 16:9 and on my browser it is very tiny.

i've tried adding the DISPLAY_HEIGHT/WIDTH variables but they don't seem to change anything

i was wondering if it is possible to change the width/height of the vnc window in the webui?

**Comment by GlassedSilver** [comment]
This could be solved (I guess) by using full noVNC instead of Lite.

In it you can set remote scaling. Although that may conflict with the display driver used here iirc.

Either way, there was SOMETHING that may make that harder to accomplish than in other containers.

That being said, if the window composition is something that someone feels like tackling, certainly not novice me I'm afraid, I'm sorry, then... IDK if you're feeling adventurous:

https://www.linuxserver.io/blog/2021-05-05-meet-webtops-a-linux-desktop-environment-in-your-browser

**Comment by Banh-Canh** [comment]
Can you guys try banhcanh/docker-fmd2:kasm-v2 ? it's cleaned up, should be much better, even though the image might be heavier.

I don't have a ci pipeline for this project so the versioning and all is manual sorry about that.

it should resize correctly now

**Comment by Jerrk** [comment]
updating to :kasm-v2 gives me this log when running the container
```
Xvnc KasmVNC 1.2.0 - built Jan 13 2024 18:57:51
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

0024:fixme:file:NtLockFile I/O completion on lock not implemented yet
012c:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x64af0f8.
0124:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] Files found, executing
[custom-init] init.sh: executing...
[custom-init] init.sh: exited 0
[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
ObRender-Message: Unable to load the theme 'Lime Night'
ObRender-Message: Falling back to the default theme 'Clearlooks'
```

trying to navigate to the webui gives the error `ERR_CONNECTION_REFUSED`.

I went back to the previous version for now.

**Comment by Banh-Canh** [comment]
did you try on port 3000 ? I changed the default port.

**Comment by Jerrk** [comment]
changed the port to 3000 and now it works, i have the same error as https://github.com/Banh-Canh/docker-FMD2/issues/13#issuecomment-1890826546 now but we can keep that issue in that topic and close this one as completed.

Thanks!
