### ISSUE TITLE
Readcomics does not download correctly

### ISSUE THREAD

**Issue by shedman214** [Banh-Canh/docker-FMD2#8]
OS: What operating system are you running Manga Tagger on?
I'm running on unraid
Manga Tagger Version: What version of Manga Tagger are you running?
v2.0.31.0
Description of the issue: Give a clear and concise description of what the issue is.
When I use Readcomics online I get an error and it does not complete. Is there another step to get the comics to download? Manga downloads fine but comics do not.
Manga Series: What manga series (singular or plural) were being tagged when the issue was encountered?
![image](https://user-images.githubusercontent.com/32603273/173962643-6c01086a-2721-4173-8bc6-a0dd83bdc7e9.png)

**Comment by Banh-Canh** [comment]
Does it run if you use the official binaries outside of docker, on Windows ?
