### ISSUE TITLE
Incorrect Mapping

### ISSUE THREAD

**Issue by HamzaM** [Banh-Canh/docker-FMD2#9]
I have setup FMD2 but it seems it is downloading it inside Wine, when I access the path I put in the docker compose, I can't find the manga as if the mapping didn't work.

This is where they download even though it is not the path i entered
![image](https://user-images.githubusercontent.com/14812057/211630298-c4bcc5f1-4c98-4054-9e36-b5d6d4f28407.png)

**Comment by Ibbanez** [comment]
Im getting the same issue inside a Docker Container in UnRaid. The /downloads is mapped to a shared folder in my UnRaid array, but its still storing everything inside Wine somewhere, although when I go look for them, I can't find them, so I'm afraid its actually inside the overall docker space that I can't get into. Not sure why this is happening. Inside the GUI, its treating /downloads as a folder inside WINE, not the mapped space. Anyone know how to fix this?

**Comment by Ibbanez** [comment]
Actually I figured it out. You have to go into the Save To section and simply click on the same folder. Wine maps it to the Z drive, but the program simply adds /downloads, so it won't work correctly. I don't know, but if you open of the browse section and click on the same exact folder, it adds it as Z:/downloads, and will map correctly and work just fine. weird.

**Comment by Banh-Canh** [comment]
I'll take a look, i believe i fixed it an experimental build of the container, sorry for the delay
